[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.0.0"

[[constraint]]
  branch = "0.6.0"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"
