on: push
name: test-and-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        go mod download

    - name: Run unit-tests
      run: |
        GO111MODULE=on CGO_ENABLED=0 go test ./...

    - name: Build executables
      run: |
        ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: binaries
        path: .build

  dockerimage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
          fetch-depth: 1      

    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: binaries
        path: .build
    
    - name: Build docker image
      run: |
        docker build . -t trustpilot/beat-exporter

