on: release
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build executables
        uses: cedrickring/golang-action/go1.13@1.3.0
        with:
          args: ./build.sh
      - name: Create artifacts 
        uses: cedrickring/golang-action/go1.13@1.3.0
        with:
          args: ./create-artifacts.sh
      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './.release/beat-exporter-*'